settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: youtubeApp-by-go
  path: .
  commands:
    install:
      status: true
      method: go build -o <path/to/built/binary>
    run:
      status: true
      method: <path/to/built/binary>
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
